<?php

namespace AppBundle\Repository;

/**
 * SommeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SommeRepository extends \Doctrine\ORM\EntityRepository
{


    public function findBigSomme()
    {

        $em = $this->getEntityManager();

        $query = $em->createQuery("Select p from AppBundle:Somme p where p.number1 > :result")->setParameter('result', '20');

        $result = $query->getResult();
        return $result;


    }
}
