# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
            AppBundle\Entity\User:
                id: app.password_encoder
    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
         in_db:
                    entity:
                        class: AppBundle:User
                        property: username

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/*, roles: ['ROLE_USER']}



    firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false

            main:
                pattern:   ^/
                anonymous: true
                provider: in_db
                form_login:
                                login_path: login
                                check_path: login
                logout:
                                path:       logout
                                target:     /login
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
